### ISSUE TITLE
Is this library working?

### ISSUE THREAD

**Issue by pupeno** [Yleisradio/new-reliquary#6]
I just added to a Heroku app and no data is showing up in new relic. I followed the documentation in the README. I haven't started debugging yet though.

**Comment by mhjort** [comment]
We have a lot of applications running with this library. However, we haven't any experience on using this with Heroku.

**Comment by pupeno** [comment]
Are you using the Ring middleware?

Heroku exposes two environment variables, NEW_RELIC_LICENSE_KEY and NEW_RELIC_LOG (not sure what that one is for). Would this library pick the licence key from an environment variable automatically?

**Comment by pupeno** [comment]
I never used newrelic in Java before, so I think I'm just missing the proper installation of newrelic in my project.

**Comment by pupeno** [comment]
Ah... got it work. I'll have a blog post coming up about how to do it at https://carouselapps.com.

**Comment by pupeno** [comment]
Here's the blog post: https://carouselapps.com/2015/09/07/using-new-relic-with-clojure/
